# Generated by Django 5.2.11 on 2026-03-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='repeat_daily',
            field=models.BooleanField(default=False),
        ),
    ]
