# Generated by Django 5.2.11 on 2026-03-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_repeat_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='audio_id',
            field=models.IntegerField(default=1),
        ),
    ]
